# Generated by Django 4.2.7 on 2026-03-23 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import schools.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSchool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('school_type', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('catholic', 'Catholic'), ('protestant', 'Protestant'), ('islamic', 'Islamic')], default='government', max_length=20)),
                ('motto', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(max_length=60)),
                ('district', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=schools.models.school_logo_path)),
                ('image', models.ImageField(blank=True, null=True, upload_to=schools.models.school_image_path)),
                ('combinations_offered', models.TextField(blank=True)),
                ('a_level_students', models.PositiveIntegerField(default=0)),
                ('o_level_streams', models.PositiveIntegerField(default=1)),
                ('year_founded', models.PositiveIntegerField(blank=True, null=True)),
                ('facilities', models.TextField(blank=True)),
                ('boarding', models.CharField(choices=[('day', 'Day Only'), ('boarding', 'Boarding Only'), ('both', 'Day & Boarding')], default='day', max_length=10)),
                ('description', models.TextField(blank=True, max_length=600)),
                ('ad_tier', models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium')], default='free', max_length=10)),
                ('is_partner', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_school', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
